# Generated by Django 5.2.5 on 2025-08-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(fields=["date", "meal_type"], name="diary_date_meal_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="food_name_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["start_date"], name="goal_startdate_idx"),
        ),
        migrations.AddConstraint(
            model_name="diaryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="diary_quantity_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("calories__gte", 0)), name="food_calories_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("protein__gte", 0)), name="food_protein_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("carbs__gte", 0)), name="food_carbs_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("fat__gte", 0)), name="food_fat_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("fiber__gte", 0)), name="food_fiber_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("sugar__gte", 0)), name="food_sugar_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("sodium__gte", 0)), name="food_sodium_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("cholesterol__gte", 0)), name="food_cholesterol_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("calorie_goal__gte", 0)), name="goal_calorie_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("protein_goal__gte", 0)), name="goal_protein_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("carb_goal__gte", 0)), name="goal_carb_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("fat_goal__gte", 0)), name="goal_fat_nonneg"
            ),
        ),
    ]
